### PR TITLE
feat(svg): animation alternative

### PR DESCRIPTION
**Pull request by danilowoz**
This introduces a new approach to animate SVG gradients and work around the new chromium limitation. 

BREAKING CHANGE: The `keyTimes`, `gradientTransform` and `animateBegin` options have been removed.

Preview: https://kn8w9s-6006.csb.app/?path=/story/react-content-loader--animate
Close https://github.com/danilowoz/react-content-loader/issues/316

### CODE REVIEW

**Comment by amoshydra** [comment]
Tested in Safari 17.3, the linear gradient does not transform. 

In Chrome 122.0.6261.94, this works reasonably well, if not identical.

**Comment by amoshydra** [comment]
@tienifr instead of user agent detection, we should be able to check for support of `gradientTransform` like this:

```tsx
const linearGradient = document.createElementNS("http://www.w3.org/2000/svg", "linearGradient");
console.log(linearGradient.gradientTransform); // return undefined on unsupported browser

const canSupportGradientTransform = !!linearGradient.gradientTransform;
```

| Browser | ReturnValue |
| -- | -- |
| Chrome 122 | `SVGAnimatedTransformList` |
| Firefox 122 | `SVGAnimatedTransformList` |
| Safari 17.3 | `undefined`

^ I am not able to test for IE for now.

**Comment by danilowoz** [comment]
I don't want to rely on the `userAgent` property because then this component would be client-only. I'm looking for a one-fit-all solution, but I'm running out of ideas :(

**Comment by danilowoz** [comment]
Maybe we can go for the `animateTransform` approach:
- Safari will support it soon - it's currently in the preview step;
- Internet Explorer, well, it's a deprecated browser;

https://caniuse.com/?search=animateTransform

**Comment by abzokhattab** [comment]
Found [this article](https://stackoverflow.com/questions/66977183/svg-animatetransform-not-working-in-safari) where in the accepted answer the author was able to make the `animateTransform` work with safari and chrome

**Comment by danilowoz** [comment]
Ok, I got it running on Safari. Turns out, the `linearGradient` element requires an initial `gradientTransform` value to trigger the animation. Plus, I misread the [caniuse.com/?search=animateTransform](https://caniuse.com/?search=animateTransform) table, and actually, Safari fully supports `animateTransform` already, so we're good to go. 

Considering deprecating the following props: 
- `keyTimes`: I can't see how to support it in this new approach, and to be honest, I have never understood how it works. Anyway this library belongs not only to me, but also to the community.
- `gradientTransform`: that's a shame, but I couldn't make it work. This is used to allow for changing the gradient orientation and the animation direction.

Another round of review? I try fixing tests meanwhile.

**Comment by abzokhattab** [comment]
Tried Chrome, Firefox, and Safari, and they all work as expected. Great job @danilowoz

**Comment by Roeefl** [comment]
@danilowoz 

feat(svg): animation alternative #317

```
+14,239 −64,905 
```

You crazy bro?

**Comment by danilowoz** [comment]
Screenshot 2024-03-07 at 13 27 20

The output in NPM will be the same

**Comment by Roeefl** [comment]
My bad. Just saw a bunch of files, where I was expecting mostly 1 file changed. 

Nicely done, great job & thanks for the quick response.

**Comment by danilowoz** [comment]
All tests and build passed! I'm going to publish a new major version soon

**Pull request merged**
