### PR TITLE
Added traditional list with bullets

### PR DESCRIPTION
**Pull request by rakeshgunduka**

### CODE REVIEW

**Comment by rakeshgunduka** [comment]
Hi @danilowoz, 
Hope this would be fine.

**Comment by danilowoz** [comment]
Nice, Thanks! Just one more thing 😄 
Could you please set the radius to `5` on the component? I think will be better 

Ahh add the new component on the Readme, thanks @rakeshgunduka!

**Comment by danilowoz** [comment]
Sorry @rakeshgunduka I forgot to say, but I think you should set `5` on rects

**Comment by rakeshgunduka** [comment]
kidding me? 😄

**Comment by rakeshgunduka** [comment]
I may not add Readme since I may not want to spend time in getting the gif of the new component.

**Comment by danilowoz** [comment]
No problem @rakeshgunduka, I'll do this!

Thanks a lot! Tomorrow I'll merge it.  🎉 🍻

**Pull request merged**
