### PR TITLE
Native: performance

### LINKED ISSUE #178: Memory leak
The components created with `react-content-loader` seem to be leaking memory. 

```
import React from 'react'
import ContentLoader, { Rect } from 'react-content-loader/native'

const LoaderSkeleton = () => (
  <View style={{ flex: 1 }}>
    <ContentLoader height={96}>
      <Rect width={64} height={64} />
      <Rect x={64 + 12} y={0} width={80} height={18} />
      <Rect x={64 + 12} y={18 + 4} width={230} height={22} />
      <Rect x={64 + 12} y={18 + 4 + 22} width={112} height={22} />
      <Rect x={64 + 12} y={18 + 4 + 22 + 22 + 12} width={160} height={18} />
    </ContentLoader>
  </View>
)

export default LoaderSkeleton
```

Screen Shot 2020-01-24 at 16 33 19

Libraries:
```
    "react-content-loader": "^4.3.4",
    "react-native-svg": "^11.0.1",
```
Is it a known issue?

### PR DESCRIPTION
**Pull request by danilowoz**
## Summary
In order to avoid too many renders on the component - which was causing some issue performance -, I've shifted the approach to use the values of `Animated` instead of an internal state. I hope it solves the performances issues as it doesn't have any extra render.

## Related Issue 
It fixes #178, also thanks to @ds8k who came up this approach.

For who is interest in this issue, it is open to be reviewed.

### CODE REVIEW

**Comment by ds8k** [comment]
Did you notice a significant improvement? I'd love to be able to test this locally. Do you have some steps I can follow to build the project?

**Comment by danilowoz** [comment]
To be honest, I didn't do intensive tests, as my free time was short. I'll do it as soon as I can, but I'm sure itI reached better results than before. 

If you would like to test it, I just release a beta version on npm, try out the `5.0.4-rc1` version.

**Comment by ds8k** [comment]
@danilowoz I installed the beta version and now it looks like all my placeholders are just white and not animating?

**Comment by ds8k** [comment]
@danilowoz Much better even in debug mode!! If I had one complaint, it's that I wish the animation started up even just a tiny bit sooner.

But honestly this is a huge improvements on its own.

**Comment by danilowoz** [comment]
@ds8k thanks for your review.
As it is an important issue, I'm going to merge no, but feel free to suggest any improvement on animation values :)

**Pull request merged**
